---
- name: Create an EC2 key
  ec2_key:
    name: "rancher-private-key"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_accesskey }}"
    aws_secret_key: "{{ aws_secretkey }}"
  register: ec2_key

- name: Create directory for private key
  file:
    path: "{{ provision_rancher.directory.artifacts }}"
    state: directory

- name: Save private Key
  copy: content="{{ ec2_key.key.private_key }}" dest="{{ provision_rancher.directory.artifacts }}/rancher-private-key.pem" mode=0600
  when: ec2_key.changed

- name: Create rancher ec2 instance
  ec2:
    key_name: "{{ ec2_key.key.name }}"
    group_id: "{{ security_group.group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ vpc_subnet.subnet.id }}"
    assign_public_ip: yes
    aws_access_key: "{{ aws_accesskey }}"
    aws_secret_key: "{{ aws_secretkey }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 50
        delete_on_termination: yes
    instance_tags:
      Name: "{{ instance_name_tag }}"
    exact_count: "1"
    count_tag:
      Name: "{{ instance_name_tag }}"
  register: rancher_ec2

- name: Save public ip address of rancher instance
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: rancher_instance_public_ip
    ansible_ssh_private_key_file: "{{ provision_rancher.directory.artifacts }}/rancher-private-key.pem"
  with_items: "{{ rancher_ec2.tagged_instances }}"

- name: Save private ip address of rancher instance
  add_host:
    hostname: "{{ item.private_ip }}"
    groupname: rancher_instance_private_ip
  with_items: "{{ rancher_ec2.tagged_instances }}"

- name: Save hostname of rancher instance
  add_host:
    hostname: "{{ item.private_dns_name }}"
    groupname: rancher_instance_hostname
  with_items: "{{ rancher_ec2.tagged_instances }}"

- name: Wait for SSH
  wait_for:
    delay: 1
    host: "{{ item.public_ip }}"
    port: 22
    state: started
    timeout: 30
  with_items: "{{rancher_ec2.tagged_instances}}"
