---
- name: Create AWS network resources
  hosts: localhost
  gather_facts: True
  roles:
  - role: provision-network
  vars_files:
  - "{{ provision_rancher.directory.configuration }}/rancher-conf/rancher_vars"
  - "{{ provision_rancher.directory.credentials }}/credentials"

- name: Create rancher instance
  hosts: localhost
  gather_facts: True
  roles:
  - role: create-rancher-instance
  vars_files:
  - "{{ provision_rancher.directory.configuration }}/rancher-conf/rancher_vars"
  - "{{ provision_rancher.directory.credentials }}/credentials"

- name: Install packages
  gather_facts: False
  hosts: rancher_instance_public_ip
  become_method: sudo
  become: yes
  remote_user: ubuntu
  roles:
  - role: install-packages
  vars_files:
  - "{{ provision_rancher.directory.configuration }}/rancher-conf/rancher_vars"
  - "{{ provision_rancher.directory.credentials }}/credentials"

- name: Deploy Rancher
  gather_facts: True
  hosts: rancher_instance_public_ip
  become_method: sudo
  become: yes
  remote_user: ubuntu
  roles:
  - role: deploy-rancher
  vars_files:
  - "{{ provision_rancher.directory.configuration }}/rancher-conf/rancher_vars"
  - "{{ provision_rancher.directory.credentials }}/credentials"
